local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/Robojini/Tuturial_UI_Library/main/UI_Template_1"))()
local Window = Library.CreateLib("Survivle Giant", "RJTheme7")
local Tab = Window:NewTab("Guns")
local Section = Tab:NewSection("CrossBow")
Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "Crossbow"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].weaponequipped
Event:FireServer(A_1)

end)

local Section = Tab:NewSection("Slingshot")

Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "Slingshot"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].weaponequipped
Event:FireServer(A_1)

end)

local Section = Tab:NewSection("Revolver")

Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "Revolver"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].weaponequipped
Event:FireServer(A_1)

end)



local Section = Tab:NewSection("Banana Pistol")

Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "Banana Pistol"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].weaponequipped
Event:FireServer(A_1)

end)


local Section = Tab:NewSection("Potato Launche")

Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "Potato Launcher"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].weaponequipped
Event:FireServer(A_1)

end)


local Section = Tab:NewSection("Paintball Gun")

Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "Paintball Gun"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].weaponequipped
Event:FireServer(A_1)

end)



local Section = Tab:NewSection("Fireworks Launcher")

Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "Fireworks Launcher"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].weaponequipped
Event:FireServer(A_1)

end)



local Section = Tab:NewSection("Double Barrel Shotgun")

Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "Double Barrel Shotgun"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].weaponequipped
Event:FireServer(A_1)

end)



local Section = Tab:NewSection("SMG")

Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "SMG"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].weaponequipped
Event:FireServer(A_1)

end)



local Section = Tab:NewSection("Plunger Rifle")

Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "Plunger Rifle"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].weaponequipped
Event:FireServer(A_1)

end)



local Section = Tab:NewSection("Minigun")

Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "Minigun"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].weaponequipped
Event:FireServer(A_1)

end)



local Section = Tab:NewSection("Sniper Rifle")

Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "Sniper Rifle"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].weaponequipped
Event:FireServer(A_1)

end)



local Section = Tab:NewSection("Lava Pistol")

Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "Lava Pistol"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].weaponequipped
Event:FireServer(A_1)

end)



local Section = Tab:NewSection("SCAR")

Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "SCAR"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].weaponequipped
Event:FireServer(A_1)

end)


local Section = Tab:NewSection("Ray Gun")

Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "Ray Gun"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].weaponequipped
Event:FireServer(A_1)

end)



local Section = Tab:NewSection("Space Rifle")

Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "Space Rifle"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].weaponequipped
Event:FireServer(A_1)

end)




local Section = Tab:NewSection("Biochemical Blaster")

Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "Biochemical Blaster"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].weaponequipped
Event:FireServer(A_1)

end)





local Section = Tab:NewSection("Golden Pistol")

Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "Golden Pistol"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].weaponequipped
Event:FireServer(A_1)

end)



local Section = Tab:NewSection("Black Hole Gun")

Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "Black Hole Gun"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].weaponequipped
Event:FireServer(A_1)

end)



local Section = Tab:NewSection("Crazy Futuristic Minigun")

Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "Crazy Futuristic Minigun"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].weaponequipped
Event:FireServer(A_1)

end)



local Tab = Window:NewTab("Gears")


local Section = Tab:NewSection("Gravity Coil")
Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "Gravity Coil"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].gearequipped
Event:FireServer(A_1)

end)



local Section = Tab:NewSection("Speed Coil")
Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "Speed Coil"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].gearequipped
Event:FireServer(A_1)

end)



local Section = Tab:NewSection("Super Gravity Coil")
Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "Super Gravity Coil"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].gearequipped
Event:FireServer(A_1)

end)

local Section = Tab:NewSection("Super Speed Coil")
Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "Super Speed Coil"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].gearequipped
Event:FireServer(A_1)

end)

local Section = Tab:NewSection("Cash Magnet")
Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "Cash Magnet"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].gearequipped
Event:FireServer(A_1)

end)

local Section = Tab:NewSection("Infinity Coil")
Section:NewButton("Click", "ButtonInfo", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "Infinity Coil"
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"].gearequipped
Event:FireServer(A_1)

end)

local Tab = Window:NewTab("Ability")
local Section = Tab:NewSection("Speed")

Section:NewSlider("Speed", "SliderInfo", 500, 0, function(s) -- 500 (Макс. значение) | 0 (Мин. значение)
    game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = s
end)

local Section = Tab:NewSection("JumpPower")
Section:NewSlider("JumpPower", "SliderInfo", 500, 0, function(s) -- 500 (Макс. значение) | 0 (Мин. значение)
    game.Players.LocalPlayer.Character.Humanoid.JumpPower = s
end)

local Tab = Window:NewTab("Telegram")
local Section = Tab:NewSection("@LiteUpiter")
